In [1]:
import pandas as pd

In [4]:
df1 = pd.read_csv("C:\\Users\\HP\\Downloads\\products.csv")
df1

,product_id,product_name,category,sub_category,unit_cost,selling_price,shipping_cost_per_unit,weight_lbs,supplier
0,SKU-0001,Headphones - Variant 1,Electronics,Headphones,29.44,56.08,13.42,12.4,Supplier A
1,SKU-0002,Headphones - Variant 2,Electronics,Headphones,26.92,91.57,15.50,15.0,Supplier B
2,SKU-0003,Headphones - Variant 3,Electronics,Headphones,15.91,43.34,9.58,7.6,Supplier C
3,SKU-0004,Headphones - Variant 4,Electronics,Headphones,7.13,24.31,5.74,2.8,Supplier B
4,SKU-0005,Headphones - Variant 5,Electronics,Headphones,43.05,135.82,5.82,2.9,Supplier C
...,...,...,...,...,...,...,...,...,...
202,SKU-0203,Sauces - Variant 5,Food & Beverage,Sauces,19.99,32.04,14.22,13.4,Supplier C
203,SKU-0204,Organic - Variant 1,Food & Beverage,Organic,13.64,27.16,11.34,9.8,Supplier B
204,SKU-0205,Organic - Variant 2,Food & Beverage,Organic,8.47,19.41,12.70,11.5,Supplier D
205,SKU-0206,Organic - Variant 3,Food & Beverage,Organic,39.68,136.04,6.30,3.5,Supplier D
206,SKU-0207,Organic - Variant 4,Food & Beverage,Organic,37.28,63.96,11.42,9.9,Supplier C

In [5]:
df2 = pd.read_csv("C:\\Users\\HP\\Downloads\\orders (1).csv")
df2

,order_id,customer_id,order_date,channel,payment_method,region,items_ordered,primary_category,gross_revenue,discount_pct,discount_amount,shipping_cost,product_cost,platform_fee,transaction_fee,returned,refund_amount,net_revenue,total_costs,profit
0,ORD-000001,C-0617,2025-06-24,Mobile App,Gift Card,Northeast,2,Electronics,261.39,0,0.00,22.28,92.30,0.00,7.88,No,0.00,261.39,122.46,138.93
1,ORD-000002,C-0720,2025-08-23,Website,Credit Card,Midwest,1,Beauty,24.02,0,0.00,3.98,10.75,0.00,1.00,No,0.00,24.02,15.73,8.29
2,ORD-000003,C-0189,2025-07-20,Website,Credit Card,Southeast,2,Toys,52.60,0,0.00,14.60,31.41,0.00,1.83,No,0.00,52.60,47.84,4.76
3,ORD-000004,C-0058,2025-07-17,Mobile App,Debit Card,Southeast,2,Sports,30.63,5,1.53,30.98,16.27,0.00,1.14,No,0.00,29.10,48.39,-19.29
4,ORD-000005,C-0580,2025-10-11,Marketplace,Credit Card,Northeast,1,Sports,11.99,25,3.00,10.30,6.88,1.35,0.56,No,0.00,8.99,19.09,-10.10
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1995,ORD-001996,C-0250,2025-09-06,Mobile App,Debit Card,Midwest,2,Electronics,178.22,0,0.00,51.04,80.51,0.00,5.47,No,0.00,178.22,137.02,41.20
1996,ORD-001997,C-0652,2025-06-27,Mobile App,Buy Now Pay Later,Midwest,3,Beauty,201.02,0,0.00,42.54,75.39,0.00,6.13,No,0.00,201.02,124.06,76.96
1997,ORD-001998,C-0473,2025-01-20,Marketplace,Credit Card,Southeast,1,Beauty,35.41,0,0.00,12.14,18.89,5.31,1.33,Yes,35.41,0.00,37.67,-37.67
1998,ORD-001999,C-0784,2025-08-14,Website,Credit Card,Northeast,2,Toys,81.67,10,8.17,27.08,36.91,0.00,2.43,No,0.00,73.50,66.42,7.08
1999,ORD-002000,C-0377,2025-11-21,Website,Credit Card,Southwest,1,Electronics,260.50,20,52.10,11.82,78.92,0.00,6.34,Yes,208.40,0.00,97.08,-97.08

In [10]:
df3 = pd.read_csv("C:\\Users\\HP\\Downloads\\marketing_spend.csv")
df3

,month,platform,spend,impressions,clicks,conversions,revenue_attributed,cpc,cpa,roas
0,2024-01,Google Ads,2676.14,303594,13271,500,43063.16,0.20,5.35,16.09
1,2024-01,Facebook Ads,1971.43,338022,7163,333,15950.86,0.28,5.92,8.09
2,2024-01,Instagram Ads,2418.95,561361,18729,748,54454.46,0.13,3.23,22.51
3,2024-01,TikTok Ads,1141.70,554273,6967,346,22369.23,0.16,3.30,19.59
4,2024-01,Email Marketing,868.82,29509,1215,58,4223.97,0.72,14.98,4.86
...,...,...,...,...,...,...,...,...,...,...
139,2025-12,Facebook Ads,7480.08,1454093,34543,2668,201086.58,0.22,2.80,26.88
140,2025-12,Instagram Ads,5671.66,910841,21625,869,91175.48,0.26,6.53,16.08
141,2025-12,TikTok Ads,3408.50,755034,18046,1171,111842.60,0.19,2.91,32.81
142,2025-12,Email Marketing,1796.66,15675,477,11,1198.99,3.77,163.33,0.67
143,2025-12,Influencer,6329.25,337538,17751,1374,103555.05,0.36,4.61,16.36

In [15]:
df2.groupby('primary_category')['order_id'].count()

primary_category
Beauty             205
Books              239
Clothing           293
Electronics        267
Food & Beverage    247
Home & Kitchen     200
Sports             292
Toys               257
Name: order_id, dtype: int64